[package]
name = "bits-io"
version = "0.1.5"
edition = "2021"
description = "Bit-level IO operations"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsw-types = { version = "0.1.11", features = ["num-traits", "std"] }
bitvec = "1.0.1"
