[package]
name = "bitcursor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1"
ux = { version = "0.1.6", git = "https://github.com/bbaldino/uX.git", branch = "master", features = ["num-traits"] }
num-traits = "0.2"
bitvec = "1.0.1"
